### ISSUE TITLE
Importing in Eclipse

### ISSUE THREAD

**Issue by faysalhossain2007** [googlesamples/android-UniversalMusicPlayer#13]
When i try to import the project in eclipse i got no error but all on a sudden when it starts to run it crashes. 
log cat says:
03-28 21:19:01.048: E/AndroidRuntime(12663): FATAL EXCEPTION: main
03-28 21:19:01.048: E/AndroidRuntime(12663): java.lang.NoClassDefFoundError: com.example.android.uamp.ui.BaseActivity$1
03-28 21:19:01.048: E/AndroidRuntime(12663):    at com.example.android.uamp.ui.BaseActivity.<init>(BaseActivity.java:163)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at com.example.android.uamp.ui.MusicPlayerActivity.<init>(MusicPlayerActivity.java:34)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at java.lang.Class.newInstanceImpl(Native Method)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at java.lang.Class.newInstance(Class.java:1319)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.Instrumentation.newActivity(Instrumentation.java:1053)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1986)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.ActivityThread.access$600(ActivityThread.java:138)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.os.Looper.loop(Looper.java:213)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at android.app.ActivityThread.main(ActivityThread.java:4787)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at java.lang.reflect.Method.invokeNative(Native Method)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at java.lang.reflect.Method.invoke(Method.java:511)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
03-28 21:19:01.048: E/AndroidRuntime(12663):    at dalvik.system.NativeStart.main(Native Method)

**Comment by mangini** [comment]
We don't support Eclipse, but I've tried importing, using the Gradle Eclipse plugin, and apparently it worked fine. Here is what I did:
open `mobile/build.gradle` and add this line right after the copyright header:

    apply plugin: 'eclipse'

then, from the main project directory, run:

    ./gradlew eclipse

This will generate Eclipse configuration files from the gradle build. At this time, you just need to go to Eclipse and "Import -> Existing Project into Workspace".

I will close this bug, since this is not supported officially. If you have more questions, post on StackOverflow (and feel free to ping me, so I can try to answer it if no one else does).
