### ISSUE TITLE
unable to import the project, it shows error 

### ISSUE THREAD

**Issue by R3333** [googlesamples/android-UniversalMusicPlayer#158]
unable to import the project, it shows error

**Comment by butlernc** [comment]
Please post the specific error. No idea what you think anyone is going to do with the info you have given/lack there of.

**Comment by phone-guruz** [comment]
Hi,

I imagine the issue R3333 is facing is a problem with Gradle as I am getting an error when I import the 
project into Android Studio 2.3.3 in Linux Mint 18.2 (x64, using Cinnamon UI)

When importing as a project, I am getting the following error:

Error:Failed to find target with hash string 'android-25' in: /home/[user]/Android/Sdk
Possible cause: Build properties not found for package Android SDK Platform 25
<a href="install.android.platform">Install missing platform(s) and sync project</a>

![error](https://user-images.githubusercontent.com/30429165/28559201-775db234-710d-11e7-9c07-96dabb9db0ab.png)

The problem lies is that I have Android-25 SDK installed, so any help with this would be appreciated.

![sdk](https://user-images.githubusercontent.com/30429165/28559193-6a191a78-710d-11e7-92cc-64b92dde4018.png)

**Comment by nic0lette** [comment]
Hi. Sorry, but the issues here are intended for problems or feature requests for the Android Universal Music Player, not for general support issues. I'd recommend checking out [Stack Overflow](http://stackoverflow.com/) and asking your question there.
