### ISSUE TITLE
mStart duration not stopping if i play single track list

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googlesamples/android-UniversalMusicPlayer#199]
mStart duration or seekbarupdate not stopping when playing single list track.

**Comment by youssefmankari** [comment]
I had the same issue. it didn't loop when you have one song. 

The issue is in LocalPlayback.java . When I removed this  line:`  if (mediaHasChanged || mExoPlayer == null ) {` , it, then, can execute the code inside this `if`.  I check if track changed. 

But, I get an other when I removed this `if`: When you toggle between play/pause, it starts from the beginning and not from where the player stopped.

**Comment by nic0lette** [comment]
Please take a look at the rewrite. I *think* this issue should have been addressed there.
