### ISSUE TITLE
Bug: No lock screen image and controls

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-UniversalMusicPlayer#227]
Each time I choose an item from the list, I can see it and the previous one flashes.
Also the notification disappears and re-appears.
In addition, each time I choose an item, I don't see its photo on the lock screen, and the notification on the lock screen doesn't have next&previous actions.
See attached video:
[device-2018-07-01-022625.zip](https://github.com/googlesamples/android-UniversalMusicPlayer/files/2152262/device-2018-07-01-022625.zip)

Are those intentional?

**Comment by nic0lette** [comment]
No, these are not intentional changes.

The flashing is related to the way I'm updating the items in the RecyclerView. I'll try to work a bit more on the UI soon. (Essentially it's setting all the properties, rather than just those that have changed. This is causing a bunch of views to be invalidated and redrawn.)

The lock screen image is related to the media session extension and something I misunderstood about it. I have a change to address this part.

The next & previous actions are missing because the lock screen seems to show only the collapsed actions, and "play/pause" is the only one tagged to be such. ([See `MediaStye.setShowActionsInCompactView()` in `NotificationBuilder`](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/23ab516133f75abcd243c7bbd5f15f2f1d8cbb35/media/src/main/java/com/example/android/uamp/media/NotificationBuilder.kt#L98))

Thank you for the report.

**Comment by nic0lette** [comment]
I'm not sure what you mean.

ExoPlayer is an Android library for performing media playback that one can include in an app, which has support for HLS, DASH, IMA, and DRM.

UAMP is a sample project showing best practices for media apps on Android, which happens to use ExoPlayer for playback.

As for why neither of them "scan for media files", ExoPlayer is a library, and so it's up to the developer to decide how to provide content to be played.

UAMP chooses, at least at the time, to provide that content by way of a [JSON file](https://storage.googleapis.com/uamp/catalog.json) with a list of songs. The main reason it does this is that some people just don't put music files on their devices, opting instead to stream music from various services. Some of these allow downloading tracks and local playback, but not in a way that UAMP would be able to take advantage of.

**Comment by AndroidDeveloperLB** [comment]
I see. Can you please give me a direction on what to look for, for actually scanning for media files , to be listed in the app ?

**Comment by nic0lette** [comment]
You might be able to [use this](https://gist.github.com/novoda/374533) as a starting point, otherwise I'd check on [Stack Overflow](https://stackoverflow.com/search?q=MediaStore.Audio).

**Comment by AndroidDeveloperLB** [comment]
Nice. Thanks.

**Comment by nic0lette** [comment]
I split out the lock screen issue from the glitches since they aren't actually related to one another. The glitch bug is captured in #230

**Comment by AndroidDeveloperLB** [comment]
ok thank you
