### ISSUE TITLE
Request: Implementation to show 'Favorite' status in FullScreenActivity

### ISSUE THREAD

**Issue by smabbas1234** [googlesamples/android-UniversalMusicPlayer#32]
There is code in MusicProvider to save and retrieve favorites. But no implementation to show the same in a UI.

Can someone include an example implementation of showing the 'Favorite' status of a song(media) in FullScreenActivity.

**Comment by n-i-x** [comment]
To display the status you can do the following in updateMediaDescription

int favoriteIcon = R.drawable.ic_star_off;
String musicId = description.getMediaId();
if (mChannelProvider.isFavorite(musicId)) {
    favoriteIcon = R.drawable.ic_star_on;
}
mFavorite.setImageResource(favoriteIcon);

To set/remove the favorite you can do the following in the onClickListener of the ImageView:

MediaController.TransportControls controls = getMediaController().getTransportControls();
controls.sendCustomAction(MusicService.CUSTOM_ACTION_THUMBS_UP, new Bundle());

**Comment by jimlee2** [comment]
@n-i-x can you explain a little more?

**Comment by mangini** [comment]
We did it on purpose, to make it clear that the UI is decoupled from the data provider (MediaBrowserService). If you run uAmp on Android Auto, you will see the Favorite icon because Android Auto shows all available custom actions.

The code provided by @n-i-x  above is a good starting point. I would just add that, instead of using previous knowledge about the "Favorite" button, you could show all custom actions in mediaController.getPlaybackState().getCustomActions(). They already come with title, icon and an ID, which you will need when calling controls.sendCustomAction(id, extras).
