### ISSUE TITLE
ic_by_genre is not displayed

### ISSUE THREAD

**Issue by rainman20** [googlesamples/android-UniversalMusicPlayer#36]
I think there is an issue with displaying the ic_by_genre icon 
In the `MusicService.java` I applied to following changes to display the icon: 

```
 .setIconUri(Uri.parse("android.resource://" +
                                    getPackageName() + "/" + R.drawable.ic_by_genre))
```
instead of the original: 
```
.setIconUri(Uri.parse("android.resource://" +
                                "com.example.android.uamp/drawable/ic_by_genre"))
```
but still does not show the ic_by_genre icon
is this a bug ?

**Comment by mangini** [comment]
This is by design. To keep the navigation cleaner, we decided to not show the MediaItem icon on the local browsing UI. Other browsing UI's may show it, like Android Auto and Android Wear. If you want to change uAmp to show the MediaDescription.getIconUri, set the holder.mImageView at https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/ui/MediaItemViewHolder.java
