### ISSUE TITLE
MediaBrowserServiceCompat with support-v4-24.1.1 doesn't works

### ISSUE THREAD

**Issue by loki666** [googlesamples/android-UniversalMusicPlayer#92]
start a track
open the FullScreenPlayerActivity
go back

W/MBServiceCompat: getMediaItem for callback that isn't registered id=**BY_GENRE**/Genre 1
W/MBServiceCompat: addSubscription for callback that isn't registered id=**BY_GENRE**/Genre 1

**Comment by molexx** [comment]
This is recreatable with support lib 25.1.0 (December 2016): clone this repo, update build.gradle to support lib 25.0.1, compile and targetSdkVersion 25, and build tools 25.0.2.

It builds and initially runs fine but if you stop and then restart the browsing activity (by going to the FullScreenPlayer as suggested above, or bring up Android's task list) tapping on an item in the browse list returns an empty list and you get the warnings below in logcat:

```
01-14 17:12:07.698 29105-29105/com.example.android.uamp W/MBServiceCompat: addSubscription for callback that isn't registered id=__ROOT__
01-14 17:12:10.628 29105-29105/com.example.android.uamp W/MBServiceCompat: removeSubscription for callback that isn't registered id=__ROOT__
01-14 17:12:10.638 29105-29105/com.example.android.uamp W/MBServiceCompat: getMediaItem for callback that isn't registered id=__BY_GENRE__
01-14 17:12:10.638 29105-29105/com.example.android.uamp W/MBServiceCompat: addSubscription for callback that isn't registered id=__BY_GENRE__
```

I think this broke in support lib 24.0.0. It seems like the first call to `MediaBrowserCompat.connect()` works fine but subsequent calls on the same MediaBrowserCompat instance don't.

Not sure if this is a bug in the support lib or if it's meant to be used in a different way.

**Comment by molexx** [comment]
This seems to only affect devices running APIs 21-23.

**Comment by molexx** [comment]
I think this is a support library bug, I've created an issue for this: https://code.google.com/p/android/issues/detail?id=232455

**Comment by hnvn** [comment]
I encountered the same problem. My temporary solution is move MediaBrowserCompat.connect() from onStart() to onCreate(), and move MediaBrowserCompat.disconnect() from onStop() to onDestroy(). It works now.

**Comment by anonym24** [comment]
@hnvn It helped a little `onLoadChildren` is being called now, but I get `SubscriptionCallback onError ***` 
I use fragment all this in fragment

**Comment by anonym24** [comment]
@hnvn helped me only a Little,  `onLoadChildren` is being called now but I get `onError MyBrowserItem` (so in my `MediaBrowserCompat.SubscriptionCallback` `onChildrenLoaded` isn't being called, but `onError` is called

**Comment by anonym24** [comment]
please help me http://stackoverflow.com/questions/43169875/mediabrowser-subscribe-doesnt-work-after-i-get-back-to-activity-1-from-activity

**Comment by hnvn** [comment]
Get me more information, because my code is running well now  
  
Sent from [Nylas Pro](https://link.nylas.com/link/ehzbiqbj8xg1wjqsffo3yo4z4
/local-938adf1b-3718/0?redirect=https%3A%2F%2Fnylas.com%2Fnylas-pro%3Fref%3Dn1
&r=cmVwbHkrMDA1MzcxNjE5M2QzMDEzMTlmNGEzN2NmMzMwZTIzZjRlMTE4ZjE5ZjIxOTg0OTJiOTJ
jZjAwMDAwMDAxMTRmOGU0ZTY5MmExNjljZTBhMmMxYWRkQHJlcGx5LmdpdGh1Yi5jb20=), the
most powerful email app for
work![](https://link.nylas.com/open/ehzbiqbj8xg1wjqsffo3yo4z4/local-938adf1b-3
718?r=cmVwbHkrMDA1MzcxNjE5M2QzMDEzMTlmNGEzN2NmMzMwZTIzZjRlMTE4ZjE5ZjIxOTg0OTJi
OTJjZjAwMDAwMDAxMTRmOGU0ZTY5MmExNjljZTBhMmMxYWRkQHJlcGx5LmdpdGh1Yi5jb20=)

  
On Apr 2 2017, at 11:12 pm, anonym24 <notifications@github.com> wrote:  

> please help me [http://stackoverflow.com/questions/43169875/mediabrowser-
subscribe-doesnt-work-after-i-get-back-to-activity-1-from-
activity](http://stackoverflow.com/questions/43169875/mediabrowser-subscribe-
doesnt-work-after-i-get-back-to-activity-1-from-activity&r=cmVwbHkrMDA1MzcxNjE
5M2QzMDEzMTlmNGEzN2NmMzMwZTIzZjRlMTE4ZjE5ZjIxOTg0OTJiOTJjZjAwMDAwMDAxMTRmOGU0Z
TY5MmExNjljZTBhMmMxYWRkQHJlcGx5LmdpdGh1Yi5jb20=)

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on
GitHub](https://github.com/googlesamples/android-UniversalMusicPlayer/issues/9
2#issuecomment-290996202&r=cmVwbHkrMDA1MzcxNjE5M2QzMDEzMTlmNGEzN2NmMzMwZTIzZjR
lMTE4ZjE5ZjIxOTg0OTJiOTJjZjAwMDAwMDAxMTRmOGU0ZTY5MmExNjljZTBhMmMxYWRkQHJlcGx5L
mdpdGh1Yi5jb20=), or [mute the thread](https://github.com/notifications
/unsubscribe-auth/AFNxYQPh2jJ6Wds2gp2DrgLTdOlI3bbCks5rr8jmgaJpZM4JiMSm&r=cmVwb
HkrMDA1MzcxNjE5M2QzMDEzMTlmNGEzN2NmMzMwZTIzZjRlMTE4ZjE5ZjIxOTg0OTJiOTJjZjAwMDA
wMDAxMTRmOGU0ZTY5MmExNjljZTBhMmMxYWRkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://git
hub.com/notifications/beacon/AFNxYaAVPXawrvIDaFYAgAPlXFUF-
MUOks5rr8jmgaJpZM4JiMSm.gif)

**Comment by anonym24** [comment]
@hnvn no it ok, your solution helped me, it works, thanks. 
Some developer of Google trying to anylyze this issue: http://stackoverflow.com/questions/43169875/mediabrowser-subscribe-doesnt-work-after-i-get-back-to-activity-1-from-activity#comment73457087_43169875

I don't really have time to give him an example, mb you have

**Comment by Vitaliy-B** [comment]
Solution to

> move MediaBrowserCompat.connect() from onStart() to onCreate(), and move MediaBrowserCompat.disconnect() from onStop() to onDestroy()

works for me too. 
In google issuetracker this issue [marked as fixed in Support Lib v 25.4.0](https://issuetracker.google.com/issues/37133265#comment3)

**Comment by wilburt** [comment]
Didn't work for me. I have asked a question about it here http://stackoverflow.com/questions/43611281/unable-to-connect-mediabrowsercompat. 

@Vitaliy-B, please where did you get support lib version 25.4.0?

**Comment by Vitaliy-B** [comment]
@wilburt I don't have support lib version 25.4.0 , I just used advised solution..

**Comment by nic0lette** [comment]
I'm going to close this as obsolete. If it happens again, please file a new issue.

**Comment by molexx** [comment]
Yes, this was fixed in the support library, thanks.
