### ISSUE TITLE
Support for older android devices, e.g., 4.1, API level 16

### ISSUE THREAD

**Issue by orionlee** [googlesamples/android-UniversalMusicPlayer#99]
The current app requires Android 4.2 (API level 17), due to the use of [Leanback UI ](https://developer.android.com/reference/android/support/v17/leanback/package-summary.html) to optimize for TV, from what I found, specifically as a theme in [styles.xml](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/res/values/styles.xml#L53)

Is there any way to make the app more universal: backward compatible to older Android devices? (somewhat like what some android support libraries do)

If not (styles seem to be defined and bound in compile time), is there any recommendation on how to generate two versions of the app, one optimized for Android TV (API level 17), and one for all others, including older devices?

Thanks.

**Comment by nic0lette** [comment]
Sorry, but there are several reasons for why UAMP's minSdkVersion is set to 17, and this version won't be changed to support older versions.

If you'd like to fork the code and add support for earlier versions it is absolutely possible, but because this is a forum for discussing issues (bugs and feature requests) with the UAMP project, I think it would be better to ask on [Stack Overflow](http://stackoverflow.com/) for an answer to your questions.
